version: '3.7'

services:
  mysql:
    container_name: monolitoddd
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=monolitoddd
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_videos_network

networks:
  adm_videos_network:

