CREATE TABLE products (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255) NOT NULL,
    PURCHASE_PRICE DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (ID)
);